import { Link } from "wouter";
import { ArrowLeft, FileText } from "lucide-react";

const LAST_UPDATED = "15 May 2025";

export default function TermsOfService() {
  return (
    <div className="max-w-3xl mx-auto py-8 px-2 animate-in fade-in duration-500">
      <Link href="/about" className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-indigo-600 transition-colors mb-8">
        <ArrowLeft className="w-4 h-4" /> Back
      </Link>

      <div className="flex items-center gap-3 mb-2">
        <div className="w-10 h-10 rounded-xl bg-violet-50 flex items-center justify-center">
          <FileText className="w-5 h-5 text-violet-600" />
        </div>
        <h1 className="text-2xl sm:text-3xl font-bold text-slate-900">Terms of Service</h1>
      </div>
      <p className="text-slate-400 text-sm mb-10">Last updated: {LAST_UPDATED}</p>

      <div className="prose prose-slate prose-sm max-w-none space-y-8">

        <Section title="1. Acceptance of Terms">
          By accessing or using College Achiever ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service. These terms apply to all users, including visitors, registered members, and contributors.
        </Section>

        <Section title="2. Description of Service">
          College Achiever is an educational platform that provides JOSAA counselling assistance tools including a college predictor, cutoff database, mock counselling simulator, and college information. All tools are provided for informational and educational purposes only.
        </Section>

        <Section title="3. Accuracy of Information">
          While we strive to provide accurate and up-to-date information, College Achiever makes no warranties or representations about the accuracy, reliability, or completeness of any cutoff data, predictions, or college information. All data is sourced from official JOSAA records but may not reflect real-time changes.<br /><br />
          <strong>Important:</strong> Predictions generated by our tools are based on historical data and are not guarantees of admission. Always verify information directly with the official JOSAA portal (josaa.nic.in) before making any decisions.
        </Section>

        <Section title="4. User Accounts">
          You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account. You agree to provide accurate information when registering and to notify us immediately of any unauthorised use of your account. We reserve the right to terminate accounts that violate these terms.
        </Section>

        <Section title="5. Prohibited Conduct">
          You agree not to:<br /><br />
          • Use the Service for any unlawful purpose<br />
          • Attempt to gain unauthorised access to any part of the Service<br />
          • Scrape, crawl, or systematically extract data without written permission<br />
          • Misrepresent your identity or affiliation<br />
          • Upload malicious code or interfere with the Service's operation<br />
          • Resell or redistribute access to the Service without authorisation
        </Section>

        <Section title="6. Intellectual Property">
          All content on College Achiever — including but not limited to the cutoff database, predictor algorithms, UI design, text, and graphics — is the property of College Achiever or its licensors and is protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works without explicit written permission.
        </Section>

        <Section title="7. Disclaimer of Warranties">
          The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. College Achiever expressly disclaims all warranties including, but not limited to, merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or that defects will be corrected.
        </Section>

        <Section title="8. Limitation of Liability">
          To the fullest extent permitted by law, College Achiever shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use or inability to use the Service, including decisions made based on predictions or data provided by the platform. Our total liability for any claims arising out of these terms shall not exceed the amount paid by you to us in the preceding 12 months (if any).
        </Section>

        <Section title="9. Third-Party Links">
          The Service may contain links to third-party websites (such as college official sites, JOSAA portal). These links are provided for convenience only. We have no control over and assume no responsibility for the content, privacy policies, or practices of third-party sites.
        </Section>

        <Section title="10. Modifications to Terms">
          We reserve the right to modify these Terms of Service at any time. We will notify users of material changes via email or a prominent notice within the application at least 7 days before the change takes effect. Continued use of the Service after changes constitutes your acceptance of the revised terms.
        </Section>

        <Section title="11. Termination">
          We reserve the right to suspend or terminate your access to the Service at our discretion if you violate these terms, engage in fraudulent activity, or for any other reason deemed necessary to protect users or the platform.
        </Section>

        <Section title="12. Governing Law">
          These Terms of Service shall be governed by and construed in accordance with the laws of India. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts in Bengaluru, Karnataka, India.
        </Section>

        <Section title="13. Contact">
          For questions about these Terms of Service:<br /><br />
          <strong>College Achiever Legal Team</strong><br />
          Email: legal@collegeachiever.in<br />
          Address: Bengaluru, Karnataka — 560 001, India
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="text-base font-bold text-slate-900 mb-2">{title}</h2>
      <p className="text-slate-600 text-sm leading-relaxed">{children}</p>
    </div>
  );
}
